### ISSUE TITLE
How to get instance qlik object?

### ISSUE THREAD

**Issue by Manfice** [q2g/ngx-extension-build#16]
In Qlik documentation tolds next:

define(['qlik'], function(qlik){
  return {...}
})

In case of this project we implements qliq configuration in main.ts file. And i can not understand how can i get instance of qlik.
Everything else work fine.

Any suggestions?

**Comment by thomashaenig** [comment]
Hi, you can find the qlik object reference in the main.ts. it is given you by the $scope object. The path to it is $scope.component.model. This is the object of the object you created. on the object you can find all function from the engin API.

**Comment by Manfice** [comment]
> Hi, you can find the qlik object reference in the main.ts. it is given you by the $scope object. The path to it is $scope.component.model. This is the object of the object you created. on the object you can find all function from the engin API.

Thank you. I understand. But what i could not understand, that how get access to backendApi or extensionApi. 
Here is described process where we can filter values, but "this.backendApi" i do not understand where is?
https://developer.qlik.com/knowledge/tutorial/extensionTutorial

I check generic object, try to find selectValues method, but attempt was failed. Please, can anyone show me how can i do it?

**Comment by thomashaenig** [comment]
you actually do not need the backendAPI or extensionAPI. All functions which are in these API’s are also in the engineAPI (I think the backend and extension API are wrapper which in the background uses the engine API). And the object you get with $scope.component.model is a object from the engineAPI.
 
You can take a look at the list box extension (https://github.com/q2g/q2g-ext-listbox/blob/master/src/q2g-ext-listboxDirective.ts line 187)

You can find the API references in the Link below:
https://help.qlik.com/en-US/sense-developer/November2019/apis/EngineAPI/services-GenericObject-SelectListObjectValues.html

**Comment by Manfice** [comment]
Hello, Thomashaenig.

I had checked links and docs about generic object in Qlik Sense. I have some common questions, which do not corresponding this issue. Can we continue our conversation using email? To keep this issue clean. 
My email: petr@manfice.ru.

**Comment by Manfice** [comment]
I found documentation how work with selections. @thomashaenig thank you a lot. 
All methods are described here: 
https://help.qlik.com/en-US/sense-developer/September2020/apis/EngineAPI/services-GenericObject-UnPublish.html

And here described an examples how to send requests and what you get in response:
https://help.qlik.com/en-US/sense-developer/September2020/Subsystems/EngineAPI/Content/Sense_EngineAPI/WorkingWithAppsAndVisualizations/SetGetProperties/add-properties.htm

Hope this links will help to other developers.

**Comment by thomashaenig** [comment]
Hi Manifice,

thanks for the update and the links
